site_name: "Giovanni Misitano"
docs_dir: "docs"
site_dir: "site"

nav:
  - Giovanni Misitano: "index.md"
  - Research Experience: "research.md"
  - Publications: "publications.md"
  - Activities and Rewards: "activities.md"
  - Education and Teaching: "education.md"
  - Dissemination: "dissemination.md"

watch:
  - docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - palette.switch
    - navigation.tabs
    - navigation.tabs.sticky
  nav_style: dark
  locale: en
  palette:
    scheme: slate
    primary: black
  logo: assets/giovanni.jpg
  favicon: assets/favicon.ico

plugins:
  - search
  - include-markdown
  - macros:
      module_name: macros/main

extra:
  macros_dir: "macros"
  data_dir: "data"

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
